#!/bin/bash
# Name of the application
NAME="gimme_web"

# Django project directory
DJANGODIR=/home/sgomes/public/GIMME-Web

# we will communicte using this unix socket
SOCKFILE=/home/sgomes/public/GIMME-Web/deploy/run/gunicorn.sock

# the user to run as
USER=sgomes

# the group to run as
GROUP=sgomes

# how many worker processes should Gunicorn spawn
NUM_WORKERS=4
TIMEOUT=10000

# which settings file should Django use
DJANGO_SETTINGS_MODULE=GIMMEWeb.settings

# WSGI module name
DJANGO_WSGI_MODULE=GIMMEWeb.wsgi
echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR

source ../env/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)

test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)

exec /home/sgomes/public/env/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--user=$USER \
--group=$GROUP \
--bind=unix:$SOCKFILE \
--timeout=$TIMEOUT \
--log-level=info \
--log-file=/home/sgomes/public/GIMME-Web/deploy/logs/gunicorn_output.log
